# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngrest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='is_this_form_dumb',
            field=models.BooleanField(default=False),
        ),
    ]
