# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngrest', '0003_auto_20161021_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='my_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
